name: Destroy the deployed service in AWS

on: workflow_dispatch

concurrency:
  group: deployment

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Serverless Deploy
        uses: serverless/github-action@master
        with:
          args: remove
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

