name: Destroy the deployed service in AWS

on: workflow_dispatch

concurrency:
  group: deployment

jobs:
  destroy:
    name: destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Destroy Service
        uses: serverless/github-action@master
        with:
          args: remove
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

